apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.original.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: lookup-api
  name: lookup-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lookup-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: lookup-api
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        image: lookup-api
        imagePullPolicy: IfNotPresent
        name: lookup-api
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
