apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.original.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: monolithtomicroservices
  name: monolithtomicroservices
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: monolithtomicroservices
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: monolithtomicroservices
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        image: monolithtomicroservices
        imagePullPolicy: IfNotPresent
        name: monolithtomicroservices
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
